Repository wildcodeschool-2025-03/js-p3-easycook, pull requests merged in 2025-07, with the labels that each got.

#24 Us04 favorite
  client/src/App.css
  client/src/components/NavBar/NavBar_Mobile.tsx
  client/src/components/NavBar/NavBar_UL.tsx
  client/src/components/app-sidebar.tsx
  client/src/components/ui/sheet.tsx
  client/src/components/ui/sidebar.tsx
  client/src/context/UserContext.tsx
  client/src/hooks/useClickOutside.ts
  client/src/hooks/useHandleFavorite.ts
  client/src/hooks/useToggle.ts
  client/src/pages/Account/EditMemberForm.tsx
  client/src/pages/Account/FavoriteMemberList.tsx
  client/src/pages/RecipeDetails/Detail.tsx
  server/src/modules/middleware/checkToken.ts
  server/src/modules/middleware/checkTokenAdmin.ts
  server/src/modules/recipe/recipeActions.ts
  server/src/modules/recipe/recipeRepository.ts
  server/src/modules/user/memberActions.ts
  server/src/modules/user/memberRepository.ts
  server/src/router.ts
Labels: bug, documentation, enhancement, Feature, Bug Fix, Add Features

#27 finie logique page course reste CSS a faire
  client/src/components/CommentRecipe.tsx
  client/src/context/UserContext.tsx
  client/src/main.tsx
  client/src/pages/List/List.tsx
  client/src/pages/List_Course/List.tsx
  client/src/types/TypeFiles.ts
  server/src/modules/list/listActions.ts
  server/src/modules/list/listRepository.ts
  server/src/router.ts
Labels: Add Features

#28 Comments + Profile + Routes + Refacto
  client/src/components/app-sidebar.tsx
  client/src/pages/Account/Account.tsx
  client/src/pages/Account/MemberAccountPage.tsx
  client/src/pages/Account/MemberCommentedList.tsx
  client/src/pages/Account/MemberFavoriteList.tsx
  server/src/modules/user/memberActions.ts
  server/src/modules/user/memberRepository.ts
  server/src/router.ts
Labels: documentation, enhancement, Feature, Add Features

#30 Css courses
  client/public/printer.png
  client/src/components/NavBar/NavBar_UL.tsx
  client/src/pages/List_Course/List.tsx
  server/src/modules/user/memberActions.ts
Labels: bug, Add Features

#34 Us05 test
  client/src/components/Admin/Add_Recipe.tsx
  client/src/components/Admin/Member.tsx
  client/src/pages/List_Course/List.tsx
  client/src/types/TypeFiles.ts
  server/src/modules/list/listActions.ts
  server/src/modules/user/memberActions.ts
  server/src/router.ts
  server/tests/install.test.ts
  server/tests/item/routes.spec.ts
Labels: bug, documentation, enhancement, Feature, Bug Fix, Add Features

#46 updating and debgugging
  README.md
  client/src/App.tsx
  client/src/components/Connexion/SignUp.tsx
  client/src/context/UserContext.tsx
  client/src/hooks/use-mobile.ts
  client/src/pages/Account/MemberFavoriteList.tsx
  client/src/pages/Admin/Admin.tsx
  client/src/services/.gitkeep
  package-lock.json
  server/src/app.ts
  server/src/modules/middleware/checkToken.ts
  server/src/modules/middleware/checkTokenAdmin.ts
  server/src/router.ts
Labels: Bug Fix
