Repository wildcodeschool-2025-03/js-p3-easycook, pull requests merged in 2025-06, with the labels that each got.

#6 Us01 accueil
  client/public/coeur.png
  client/public/filtrer.png
  client/public/rechercher.png
  client/src/App.css
  client/src/components/HowWorks.tsx
  client/src/components/NavBar/NavBar_Mobile.tsx
  client/src/components/OurSelection.tsx
  client/src/components/SearchAccueil.tsx
  client/src/pages/Home/Home.tsx
  client/src/pages/RecipeDetails/Recipe.tsx
  client/src/types/TypeFiles.ts
  server/database/fixtures/AbstractSeeder.ts
  server/src/modules/recipe/recipeActions.ts
  server/src/modules/recipe/recipeRepository.ts
  server/src/router.ts
  server/tests/install.test.ts
  server/tests/item/routes.spec.ts
Labels: Feature

#8 finished accueil
  client/package.json
  client/src/App.css
  client/src/App.tsx
  client/src/components/AccueilCategory.tsx
  client/src/components/Banner.tsx
  client/src/components/NavBar/NavBar_Mobile.tsx
  client/src/components/OurSelection.tsx
  client/src/components/SearchAccueil.tsx
  client/src/pages/Contact/Contact.tsx
  client/src/pages/Contact/Contact_Form.tsx
  client/src/pages/Home/Home.tsx
  client/src/types/TypeFiles.ts
  client/tsconfig.json
  package-lock.json
  server/src/modules/recipe/recipeActions.ts
  server/src/modules/recipe/recipeRepository.ts
  server/src/router.ts
Labels: Feature

#10 Add all recipe on Recipe_Page
  client/src/components/Banner.tsx
  client/src/components/OurSelection.tsx
  client/src/main.tsx
  client/src/pages/RecipeDetails/Recipe.tsx
  client/src/types/TypeFiles.ts
  package-lock.json
  server/src/modules/recipe/recipeActions.ts
  server/src/modules/recipe/recipeRepository.ts
  server/src/router.ts
Labels: Add Features

#11 Us02 member login
  client/package.json
  client/src/App.tsx
  client/src/components/Connexion/LogIn.tsx
  client/src/components/Connexion/SignUp.tsx
  client/src/components/Connexion/loginForm.tsx
  client/src/components/NavBar/NavBar_UL.tsx
  client/src/components/ui/button.tsx
  client/src/components/ui/card.tsx
  client/src/components/ui/input.tsx
  client/src/components/ui/label.tsx
  client/src/context/UserContext.tsx
  client/src/main.tsx
  client/src/pages/Account/Account.tsx
  client/src/types/TypeFiles.ts
  package-lock.json
  server/src/app.ts
  server/src/modules/user/memberActions.ts
  server/src/modules/user/memberRepository.ts
  server/src/modules/user/userActions.ts
  server/src/modules/user/userRepository.ts
  server/src/router.ts
Labels: enhancement, Bug Fix, Add Features

#12 Token Context
  client/src/components/Connexion/loginForm.tsx
  client/src/components/OurSelection.tsx
  client/src/context/UserContext.tsx
  client/src/pages/Account/Account.tsx
  client/src/pages/RecipeDetails/Recipe.tsx
  server/.env.sample
  server/package.json
  server/src/modules/diet/dietRepository.ts
  server/src/modules/list/listRepository.ts
  server/src/modules/middleware/security.ts
  server/src/modules/recipe/recipeActions.ts
  server/src/modules/user/memberActions.ts
  server/src/router.ts
  server/src/types/express/index.d.ts
Labels: enhancement, Bug Fix, Add Features

#17 Dashboard_purge + Bug fix Login
  client/src/App.css
  client/src/components/Connexion/loginForm.tsx
  client/src/components/app-sidebar.tsx
  client/src/components/ui/separator.tsx
  client/src/components/ui/sidebar.tsx
  client/src/components/ui/skeleton.tsx
  client/src/pages/Account/Account.tsx
Labels: Bug Fix, Add Features

#20 Account modification componnent + Dashboard Bugs Fixed
  client/src/components/app-sidebar.tsx
  client/src/context/UserContext.tsx
  client/src/pages/Account/Account.tsx
  client/src/pages/Account/Edit_Member_Form.tsx
  client/src/pages/Account/FavoriteMemberList.tsx
  server/database/schema.sql
  server/src/modules/user/memberActions.ts
  server/src/modules/user/memberRepository.ts
  server/src/router.ts
Labels: documentation, Bug Fix, Add Features
